### ISSUE TITLE
連絡掲示板

### ISSUE THREAD

**Issue by hangingman** [Hiroyuki-Nagata/XrossBoard#1]
何か連絡があればここに書き込む

**Comment by hangingman** [comment]
月曜日までネット環境ないです~( ~´･ω･`)~

**Comment by hangingman** [comment]
やっと開発できるわ

**Comment by vabock** [comment]
0f58beea604cc51ff0b2a26c5cc237775387b2b9 がビルドできません。ビルドできないコードをコミットしないようにしてください。途中のコードをコミットするのはブランチを切ってやりましょう。
一部のソースファイルに実行属性が付いています。これはCygwin/MinGW環境でコミットすると発生する事象で`core.filemode`を`false`に設定すると回避できます。ただし、ファイル属性の変更を無視するようになるので、シェルスクリプトなどの実行属性付きのファイルをコミットする場合はLinux/Mac環境で行う必要があります。
`pull`コマンドの引数に`--rebase`を指定すると`pull`と同時に`rebase`してくれるので e95ffa4017420f8c3b46e5329d0005232a06d14c みたいな無駄なマージがなくなります。
`--rebase`オプションを付けなくても自動で実行されるようにするには

```
$ git config --global pull.rebase true
```

**Comment by hangingman** [comment]
了解しました
`git config --global pull.rebase true` これいいですね

**Comment by hangingman** [comment]
いろいろやった結果ビルド時間が少し短縮された  

### clang

`5 min 20 sec` → `3 min 8 sec`

### gcc

`3 min 51 sec` → `3 min 46 sec`

**Comment by hangingman** [comment]
レポジトリがちょっとおかしいので今はコミットしないでください

**Comment by hangingman** [comment]
直ったみたいです、原因わからず
たぶんpush -f したからかな

**Comment by vabock** [comment]
`BFG`はどうしたんですか?昨日あったdevelopブランチには`BFG`が掛っていましたが。

**Comment by hangingman** [comment]
使ってみたけどうまく行ってないみたい
手動で削除したほうがいいかも

**Comment by vabock** [comment]
手動とは?
こちらでやりましょうか?。履歴が書き変わるのでforce pushが必要です。

**Comment by hangingman** [comment]
お願いしていいでしょうか…

**Comment by vabock** [comment]
じゃあ、やりますよ

**Comment by vabock** [comment]
出来ました。これで[First commit](https://github.com/Hiroyuki-Nagata/XrossBoard/tree/3beea58c23f5b86e661e9db661b898d5ca59c5ad)から`JaneClone.exe`が消えました

**Comment by vabock** [comment]
一度、リポジトリをfetchしなおしてくださいね

**Comment by hangingman** [comment]
了解です、
ありがとうございます
これでclone処理が早くなりそうですね

**Comment by hangingman** [comment]
【専ブラ】JaneView更新、Open2ch, Next2chに対応＆2ch.netのAPI対応表明ｷﾀ━━━━(ﾟ∀ﾟ)━━━━!!!! [転載禁止]©2ch.net   [592229486]
http://fox.2ch.net/test/read.cgi/poverty/1425259154/

Viewすげえな
頑張らなくては

**Comment by vabock** [comment]
`src/xrossboard*.[ch]pp`の履歴が元の`janeclone〜`から引き継がれていません。 753c12e20f3a6b2cfa72f0a936fea5e4e3a6fa29 で新しい名前で追加して後の f5442047ca4b390d2af1aee2e4a2c00efce992b5 で古い名前のファイルが削除されています。追加と削除を同じコミットで行わないとgitがファイル名の変更を認識しません。直すにはrebaseによる歴史改変が必要です。

**Comment by hangingman** [comment]
履歴を遡ることはあまりないので問題ないと思います

**Comment by vabock** [comment]
あなたはそうかもしれませんが、普通は困るんですよ…

**Comment by hangingman** [comment]
履歴が汚いので一旦rebaseします
作業完了
