### ISSUE TITLE
Mingw用のビルドサーバがほしい

### ISSUE THREAD

**Issue by hangingman** [Hiroyuki-Nagata/XrossBoard#8]
XrossBoardはソースコードの構造上、Windows上でmsys2を使用するか、Linux上でクロスコンパイルすると簡単にパッケージ化できる。それをTravisでやるのはマシンパワー使いすぎるし難しいため、できるだけタダでJenkinsサーバなどを構築しパッケージ化を自動化したい。

**Comment by hangingman** [comment]
- 構築中  
  https://v157-7-84-235.z1d11.static.cnode.jp/jenkins/
- スクリプト  
  https://gist.github.com/Hiroyuki-Nagata/57349586faa78843422e

**Comment by hangingman** [comment]
完了した
Bintrayにzip形式のバイナリをアップロードできるようになった。
https://bintray.com/hiroyuki-nagata/generic/XrossBoard/view

**Comment by vabock** [comment]
bintrayの64bit版が次のエラーで起動できません

```
---------------------------
xrossboard.exe - システム エラー
---------------------------
コンピューターに libssp-0.dll がないため、プログラムを開始できません。この問題を解決するには、プログラムを再インストールしてみてください。 
---------------------------
OK   
---------------------------
```

**Comment by hangingman** [comment]
面倒なバグを踏んだかな
https://bugzilla.redhat.com/show_bug.cgi?id=822312

まだ未検証

**Comment by hangingman** [comment]
libsspをdllとして配布するように変更しました。
gcc-4.8からstack-protectorを使う場合そうなったみたい
